apiVersion: v1
kind: Service
metadata:
  name: laravel-svc
  namespace: laravel
  labels:
    app: laravel
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30007
    protocol: TCP
  selector:
    app: laravel

