apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: mariadb:11.4.1-rc
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: laravel-env
              key: LARAVEL_DATABASE_NAME
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USERNAME
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD

        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        ports:
        - containerPort: 3306
