apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: laravel
  labels:
    app: mariadb-app
spec:
  selector:
    app: mariadb-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306