apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      containers:
      - name: mariadb-app
        image: mariadb:11.4.1-rc
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: laravel-env
              key: LARAVEL_DATABASE_NAME
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: laravel-env
              key: LARAVEL_DATABASE_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_DATABASE_PASSWORD

        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_ROOT_PASSWORD
        ports:
        - containerPort: 3306
