apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: laravel
  labels:
    app: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306