apiVersion: v1
kind: Service
metadata:
  name: php-svc
  namespace: phpmyadmin
  labels:
     app: php
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
     app: php

   